name: Godot

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # - name: install Godot
      #   run: ./deploy.sh install

      - name: setup Microsoft Store CLI
        uses: microsoft/microsoft-store-apppublisher@v1.3

      # - name: package artifacts
      #   run: ./deploy.sh package

      - name: create release
        run: ./deploy.sh release
        env:
          GH_TOKEN: ${{ github.token }}
          MSSTORE_TENANT_ID:     "${{ secrets.TENANT_ID }}"
          MSSTORE_SELLER_ID:     "${{ secrets.SELLER_ID }}"
          MSSTORE_CLIENT_ID:     "${{ secrets.CLIENT_ID }}"
          MSSTORE_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
