name: Godot

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # - name: install Godot
      #   run: ./deploy.sh install

      - name: setup Microsoft Store CLI
        uses: microsoft/microsoft-store-apppublisher@v1.3

      - name: setup keyring
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-0 # gnome-keyring dbus dbus-x11
          eval $(dbus-launch --sh-syntax)
          echo "pipeline_fallback_password" | gnome-keyring-daemon --unlock
          eval $(echo "pipeline_fallback_password" | gnome-keyring-daemon --start --components=secrets)

          msstore reconfigure \
            --tenantId     "${{ secrets.TENANT_ID }}" \
            --sellerId     "${{ secrets.SELLER_ID }}" \
            --clientId     "${{ secrets.CLIENT_ID }}" \
            --clientSecret "${{ secrets.CLIENT_SECRET }}"

      # - name: package artifacts
      #   run: ./deploy.sh package

      - name: create release
        run: ./deploy.sh release
        env:
          GH_TOKEN: ${{ github.token }}
